create extension if not exists pgcrypto;

create table if not exists public.companies (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  legal_name text,
  tax_id text,
  address text,
  city text,
  phone text,
  email text,
  logo_path text,
  logo_source text,
  invoice_footer text,
  legal_info text,
  fiscal_settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1
);

create table if not exists public.warehouses (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  code text,
  city text,
  address text,
  description text,
  is_default boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1
);

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  description text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  name text not null,
  sku text,
  barcode text,
  description text,
  category_id uuid references public.categories(id) on delete set null,
  category_name text,
  brand text,
  unit text,
  purchase_price_ht numeric(14,3) not null default 0,
  sale_price_ht numeric(14,3) not null default 0,
  tva_rate numeric(5,2) not null default 19,
  stock_minimum numeric(14,3) not null default 0,
  image_path text,
  is_active boolean not null default true,
  stock_tracked boolean not null default true,
  serial_tracked boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1
);

create table if not exists public.partners (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  type text not null check (type in ('client', 'supplier')),
  name text not null,
  phone text,
  email text,
  tax_id text,
  address text,
  customer_type text,
  company_name text,
  contact_name text,
  city text,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1
);

create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  type text not null,
  status text not null,
  number text not null,
  sequence bigint,
  partner_id uuid references public.partners(id) on delete set null,
  partner_name text,
  partner_tax_id text,
  partner_address text,
  issue_date timestamptz not null default now(),
  due_date timestamptz,
  warehouse_id uuid references public.warehouses(id) on delete set null,
  subtotal_ht numeric(14,3) not null default 0,
  total_discount numeric(14,3) not null default 0,
  total_tva numeric(14,3) not null default 0,
  timbre_fiscal numeric(14,3) not null default 0,
  total_ttc numeric(14,3) not null default 0,
  paid_amount numeric(14,3) not null default 0,
  remaining_amount numeric(14,3) not null default 0,
  notes text,
  source_document_id uuid references public.documents(id) on delete set null,
  source_number text,
  stock_applied boolean not null default false,
  apply_timbre_fiscal boolean not null default false,
  company_snapshot jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1
);

create table if not exists public.document_lines (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  document_id uuid not null references public.documents(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  position integer not null default 0,
  label text not null,
  sku text,
  quantity numeric(14,3) not null default 0,
  unit_price_ht numeric(14,3) not null default 0,
  discount numeric(14,3) not null default 0,
  tva_rate numeric(5,2) not null default 19,
  total_ht numeric(14,3) not null default 0,
  total_tva numeric(14,3) not null default 0,
  total_ttc numeric(14,3) not null default 0,
  serial_numbers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  document_id uuid not null references public.documents(id) on delete cascade,
  amount numeric(14,3) not null default 0,
  method text,
  date timestamptz not null default now(),
  reference text,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1
);

create table if not exists public.stock_movements (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  product_name text,
  warehouse_id uuid not null references public.warehouses(id) on delete restrict,
  quantity_delta numeric(14,3) not null,
  type text not null,
  reason text,
  direction text,
  document_number text,
  source_document_id uuid references public.documents(id) on delete set null,
  note text,
  serial_numbers jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1
);

create table if not exists public.audit_events (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  type text not null,
  title text not null,
  description text,
  actor text,
  action text,
  target text,
  detail text,
  entity_type text,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1
);

create table if not exists public.settings (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  key text not null,
  value_json jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1,
  unique (tenant_id, key)
);

create table if not exists public.files (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  bucket text not null,
  path text not null,
  type text not null,
  linked_entity_type text,
  linked_entity_id uuid,
  size_bytes bigint,
  mime_type text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  version bigint not null default 1,
  unique (bucket, path)
);
